### ISSUE TITLE
import toroidal sgf

### ISSUE THREAD

**Issue by goplayerjuggler** [bernds/q5Go#1]
I had a look at v0.4; I'm particularly interested on it's features for toroidal boards. Is it possible to import SGF for a game on this sort of board?
I also posted this identical question on the L19 forum. Sorry for the duplicate but I tend to go on github a little more often than on L19...

**Comment by bernds** [comment]
Replied on lifein19x19.com already. To change a normal SGF file into a toroidal one, one has to replace GM[1] with GM[q5go-1] and add a TO[3] property to the root (TO[2] or TO[1] if only one axis is toroidal).
