### ISSUE TITLE
Save/restore layout doesn't fully work, loses some settings

### ISSUE THREAD

**Issue by blamarche** [bernds/q5Go#11]
When I customize the layout of the game/board window it fails to save completely, and also fails to apply as the default when a new game window is opened.

Specific reproduce steps:

1. Open a game to watch on IGS.
2. Click View menu, disable status bar, slider, observers. 
3. Click View menu, save as default layout.
4. Close game and/or q5go. 
5. Run again open another game, layout shows all the disabled panels again. 
6. View menu - Restore layout, mostly works but slider and status bar stay visible and this must be done for each opened game.

My preference is to maximize the vertical screen space the board is able to occupy.

**Comment by bernds** [comment]
There are some historical remnants of how qGo used to handle this. The slider at least is a preferences option so you can disable it globally. Maybe that should be deleted and the state of statusbar/slider/menubar should be part of the saved layout.

**Comment by blamarche** [comment]
Sure that would work. The observers pane is the biggest 'offender' of the vertical space. If that were able to dock on the right sidebar or save/restore default visibility would be a big improvement.

**Comment by bernds** [comment]
You should already be able to move the observers and other docks (comments, game tree) around as you wish.

**Comment by blamarche** [comment]
So it does! Thanks again for porting such a nice tool over to qt5.

**Comment by bernds** [comment]
I've removed nearly all traces of the old qGo way of handling this. Slider, sidebar, menubar and status bar visibility is now saved/loaded with the rest of the layout.

**Comment by blamarche** [comment]
Awesome, thanks!
