### ISSUE TITLE
Add option to customize stone shadows in 3d styles

### ISSUE THREAD

**Issue by blamarche** [bernds/q5Go#12]
Would be great to be able to set the shadow intensity and x/y offset from the stone (as well as disable the shadow entirely if desired).

**Comment by bernds** [comment]
Would that really make a big difference? There are already ideas to add stone pictures or shading presets to the options, and at some point I feel users are going to feel the preferences dialog is way overloaded.

I think the program should make it easy to achieve a good-looking display, and turning off shadows makes it look pretty awful in my eyes, so I don't see the value.

**Comment by blamarche** [comment]
Perhaps just a single slider for the shadow opacity level to keep it simple then. Its funny, I personally think the shadows make the board state less readable overall. Playing on a real board, unless you have a pretty strong spot light at a shallow angle, the shadows that a real stone makes can be pretty understated.
