### ISSUE TITLE
challenge, accept, no board

### ISSUE THREAD

**Issue by Lecale** [bernds/q5Go#15]
A problem I have. Challenge player I do. They accept, but no board appears. Perhaps I am missing something, but it feels a bit like I can't use version 0.8.1 to start a game. Perhaps I do something stupid

nmatch A W 9 19 600 180 25 0 0 0
Requesting nmatch with A(W 9 19 600 180 25 0 0 0).

Game 167 (I): A [ 5k?] vs B [14k ]
TIME:167:A(W): 0 600/600 0/180 25/25 0/0 0/0 0/0
TIME:167:B(B): 0 600/600 0/180 25/25 0/0 0/0 0/0
GAMERPROPS:167: 19 0 -5.50
A B C D E F G H J K L M N O P Q R S T      H-cap 0 Komi -5.5
19 |. . . . . . . . . . . . . . . . . . .| 19  Captured by #: 0
18 |. . . . . . . . . . . . . . . . . . .| 18  Captured by O: 0
17 |. . . . . . . . . . . . . . . . . . .| 17
16>|. . . + . . . . . + . . . . .>+<. . .|<16  Wh Time 10:00
15 |. . . . . . . . . . . . . . . . . . .| 15  Bl Time 10:00
14 |. . . . . . . . . . . . . . . . . . .| 14
13 |. . . . . . . . . . . . . . . . . . .| 13   Last Move:
12 |. . . . . . . . . . . . . . . . . . .| 12    #0 O (White)
11 |. . . . . . . . . . . . . . . . . . .| 11
10 |. . . + . . . . . + . . . . . + . . .| 10
9 |. . . . . . . . . . . . . . . . . . .|  9
8 |. . . . . . . . . . . . . . . . . . .|  8
7 |. . . . . . . . . . . . . . . . . . .|  7
6 |. . . . . . . . . . . . . . . . . . .|  6
5 |. . . . . . . . . . . . . . . . . . .|  5
4 |. . . + . . . . . + . . . . . + . . .|  4
3 |. . . . . . . . . . . . . . . . . . .|  3
2 |. . . . . . . . . . . . . . . . . . .|  2
1 |. . . . . . . . . . . . . . . . . . .|  1
A B C D E F G H J K L M N O P Q R S T
games 167
Match [167] with B in 10 accepted.
Please use say to talk to your opponent -- help say.
A B C D E F G H J K L M N O P Q R S T

167 5 0 19150.00 19150.00 19150.00

**Comment by bernds** [comment]
Is this on IGS (Pandanet)? I tested match requests on other servers and automatch on IGS, but match requests on IGS may still be untested. If you want to help me test, send me an email with your IGS username and I'll try to challenge you while collecting debugging information.

**Comment by Lecale** [comment]
Hello Bernd,

The problem is indeed on IGS. There I am using the account hogweed. If you
could challenge that one, perhaps we can see what went wrong. Thank you for
looking at this.

Regards,
Ian

**Comment by bernds** [comment]
I haven't seen you online yet, and stats hogweed suggests you haven't been on recently. Maybe we should arrange something?
There's something that strikes me as odd about what you posted - where did you get that output, in the messages window? You shouldn't be getting an ASCII board from the server unless it thinks you are not using a client. Did you do anything unusual (any server commands entered manually, for example)?

**Comment by bernds** [comment]
I've now tested nmatch on IGS, and I can't reproduce this behaviour. Please reopen with additional information if the problem reoccurs.
