### ISSUE TITLE
Single-window/tabbed mode option

### ISSUE THREAD

**Issue by blamarche** [bernds/q5Go#16]
Would it be feasible to add an option to merge all windows into a tabbed layout? Other than the obvious of keeping window manager clutter down, this would also help make streaming through OBS easier.

**Comment by bernds** [comment]
I know it's something that some people would like, but I haven't really put a lot of thought into how it would look in this program. Personally I'm fine with windows so I'm not entirely sure what it should look like. When you say "all windows" - what do you mean? All board windows, or the client window too?

For OBS would it help to have customizable window titles?

**Comment by blamarche** [comment]
It might help to have the window titles customizable but if multiple games were opened up it wouldn't know which one to pick since the titles could match. If the titles don't match, then we're basically right back to where we are now as far as OBS goes where every game that gets opened the user would need to update what OBS is looking at.

I would imagine it would look essentially like a web browser with a row of tabs either at the top or bottom of the window allowing to switch between the children. In my mockups below they are at the bottom

![Untitled](https://user-images.githubusercontent.com/623830/57705771-75e69980-7632-11e9-8102-061087d1da18.jpg)

![Untitled2](https://user-images.githubusercontent.com/623830/57705781-7aab4d80-7632-11e9-817d-e8cc79ba3ba5.jpg)

**Comment by bernds** [comment]
One issue is that the menus differ between the various windows, and switching them out is not something I've seen before. I'd like to avoid unusual/surprising user interface design.
It would be easier if it was restricted to board windows only, but even then I suspect it would involve a fair amount of restructuring. I'll think about it.

**Comment by blamarche** [comment]
The entire game-relevent top menu could be relegated to a Game submenu that is greyed out/hidden when not on a game tab. The menu while in a game is probably the least used function of that screen and most of the entries have equivalent functions exposed elsewhere in the game UI

**Comment by bernds** [comment]
There is now a new feature where multiple games can be observed in a single window. Let me know if this goes in the direction of what you had hoped for.
For things like OBS, would it help if you could set fixed window titles in the preferences?

**Comment by blamarche** [comment]
Yes! That could help if it could be set specifically for the window containing games.

**Comment by bernds** [comment]
I'll go ahead and close this now, as I think it's about as far as I want to go - the idea of a single window for everything does not appeal to me for the reasons mentioned earlier. But please let me know if you have additional ideas, and if you do stream, drop me a link.
