### ISSUE TITLE
Only a fraction of moves have sound.

### ISSUE THREAD

**Issue by acosmicjoke** [bernds/q5Go#17]
When sound is turned on there is sound only for about 1/4 of the moves. These moves that have sound seem to be randomly distributed. It is quite annoying because sometimes when i'm reading i don't immediately realize when my opponent makes a move. Looking at the source it doesn't seem like intended behavior, but i couldn't figure out why it is happening. I tried removing the switch statement and making it play only one kind of stone sound, and setting local_stone_sound permanently to 1 but these didn't fix the issue.

**Comment by bernds** [comment]
I have been suspecting that the sound files are too short and sometimes don't get played correctly. You could help verify that by swapping them out for longer sound files and seeing if those get played.

**Comment by acosmicjoke** [comment]
It looks like an issue with pulseaudio because the sound was working on windows. Padding out the sound files a bit fixed the problems.
