### ISSUE TITLE
Unable to write messages

### ISSUE THREAD

**Issue by acosmicjoke** [bernds/q5Go#19]
Using the latest git version, I'm unable to write messages when playing or observing games. The small message window doesn't appear. There is no such issue with the 0.9 release version.

**Comment by bernds** [comment]
By small message window, do you men the stats/talk tabs in the client window?

What exactly are the steps to reproduce? For example, right-click on a player name, "stats" should still open those tabs.

**Comment by acosmicjoke** [comment]
No, the talk tab in the client window still works for me. I mean that during playing or observing a match there used to be a small white rectangle at the bottom of the comments window where you could type your message, this doesn't appear in the newest version for me. The messages of my opponent still show up in the comments window, but there is no way to message back in game. This all happens on pandanet for me, i haven't tried any other servers yet. You could try starting a game on pandanet to see if you can reproduce this bug.

**Comment by bernds** [comment]
Whoops. Thanks for testing.

**Comment by bernds** [comment]
Actually, would you be available on IGS/Pandanet at some point to test things like adjourning/resuming games, or whether issue #15 can be reproduced? My account on IGS is venkman.

**Comment by acosmicjoke** [comment]
Sure, i can help with that. My account name is Cosmic1, i'll be online this evening (central european time).
