### ISSUE TITLE
Compilation fails on navclicked.png 

### ISSUE THREAD

**Issue by cleinias** [bernds/q5Go#2]
I am trying to compile q5go on an Archlinux system, following the suggested mkdir/qmake/make procedure. Compilation fails with:
make: *** No rule to make target '../src/images/boardwindow/navclicked.png', needed by 'qrc_q4go.cpp'.  Stop.

In fact that file is nowhere to be found in the sources. Once I added  a dummy png compilation succeeded. However, it would be nice to have the right image...

**Comment by bernds** [comment]
Should be fixed now. Sorry!
