### ISSUE TITLE
Invalid reponse from GTP engine?

### ISSUE THREAD

**Issue by peterpans2013** [bernds/q5Go#21]
![image](https://user-images.githubusercontent.com/31445699/65734755-abca7d00-e0fe-11e9-9b28-57229896425c.png)
Can you help me how to use go engine? I got this issue and don't know what to do.

**Comment by bdrose** [comment]
You need the Executable to point to the exe
`C:/yourPath/katago.exe `
Then you need to have Arguments
`gtp -model C:/yourPath/yourNeuralNet.txt.gz -config C:/yourPath/gtp_example.cfg`

**Comment by peterpans2013** [comment]
> You need the Executable to point to the exe
> `C:/yourPath/katago.exe `
> Then you need to have Arguments
> `gtp -model C:/yourPath/yourNeuralNet.txt.gz -config C:/yourPath/gtp_example.cfg`

Thank you very much.

**Comment by bernds** [comment]
I'm assuming this is solved. Thanks bdrose.
