### ISSUE TITLE
Features for easier time management. 

### ISSUE THREAD

**Issue by acosmicjoke** [bernds/q5Go#24]
The official pandanet client has this helpful feature that changes the color of your clock if your time remaining/moves remaining value goes under a certain threshold. Also, clients for some other servers can display the time remaining on top of the last played stone if you have only a few seconds left. This is very useful for blitz. Would it be possible to implement something like these in q5go?

**Comment by bernds** [comment]
I think there's already a setting that makes the time blink when it gets low. Displaying it on top of the last stone should be possible.

**Comment by acosmicjoke** [comment]
Thanks.
As I see it, there is only an option to play a ticking sound when the absolute time gets low. For me, this sometimes isn't enough with Canadian byo yomi. For example, maybe I have a long think in the first few moves of a byo yomi period after which I have say 5 minutes for 20 moves. Basically I have to blitz for the rest of the period but by the time I actually notice this sometimes it's already too late. That is why it would be nice to have some sort of warning tied specifically to the time/moves remaining value.

**Comment by bernds** [comment]
I think this takes care of it. Let me know if anything else is missing.
