### ISSUE TITLE
Feature request: more details of errors in malformed SGF files

### ISSUE THREAD

**Issue by hanysz** [bernds/q5Go#26]
On loading an SGF, sometimes q5go pops up a dialog box saying "Errors found in SGF file".  Often this is for files that load quite happily in other applications (e.g. Lizzie, CGoban, Jago).  Is it possible to include a bit more information in this dialog box, so it's easier to track down inconsistencies in how the SGF standard is used?  I have no problem with q5go enforcing a stricter interpretation of the standard than others, but the error reporting could be a bit friendlier!

(In some cases, after a lot of trial and error, I've found that Jago is inserting "FF[1]" tags that q5go doesn't like.  If I just delete those four characters of the SGF using a text editor, the file loads with no problems.)

**Comment by bernds** [comment]
It's sometimes difficult to predict what problems can occur. q5go warns on certain recoverable errors, see warn_errors in main.cpp.
FF[1] is a really old file format version of SGF that was obsoleted by FF[3] in 1993, and I'd argue that if Jago is writing these, it's a defect in Jago. If you have any other example files that can't be read for a different issue, please attach them.

**Comment by hanysz** [comment]
I think Jago is using a minimal subset of SGF that hasn't changed in FF[3].  I've never had a problem with Jago files in other applications.  But if I'm the only person affected, and it's not an easy fix, then don't worry about it.  I'll let you know if I run into any other problems.  Thanks for following up.

**Comment by bernds** [comment]
Just ignoring FF[1] when it occurs would be an easy fix, but not a good one. A good fix would involve investigating all the differences between file formats (some of which are problematic for the parser) and verifying them against real examples (not just files that would be identical between FF[3] and FF[1]), which I don't have.
Jago has an option "Save pure SGF", which is oddly worded but makes it write out FF[4]. Ideally the program would be updated to make that the default and remove the option, but I think it's a good enough workaround, so I don't think I'll be implementing an FF[1] reader. It might be a good idea though to diagnose the issue more specifically.

**Comment by hanysz** [comment]
Ah, I hadn't noticed that option within Jago!  Thanks, I'm very happy with that as a workaround.
