### ISSUE TITLE
Ensure client mode for IGS connection

### ISSUE THREAD

**Issue by colingeniet** [bernds/q5Go#32]
When an IGS connection is in verbose mode (`toggle verbose 1`), game moves are send as nice ASCII art, which is not recognized by the parser. When that occurs, the board windows simply never show after accepting/observing a game.

The problem is that on IGS, the verbose setting seems to be persistent across sessions. Thus if I e.g. turn it on because I was connecting to IGS with telnet, and then connect with q5go, it will still be in verbose mode, and fail. (This took me longer to debug than I am willing to admit)

Enabling client mode `toggle client 1` when starting the connection seems like a sensible way to avoid this.

I have yet to check whether this applies to NNGS in general, or is specific to IGS.

**Comment by colingeniet** [comment]
This is the same issue as #15 which was closed due to lack of information (sorry for duplicate).

**Comment by bernds** [comment]
Should be fixed now.
