### ISSUE TITLE
q5go doesn't save layout properly

### ISSUE THREAD

**Issue by nsklaus** [bernds/q5Go#34]
i configured the layout so when i play on igs, the side bar is on the right, and the comment (chat) bar is on the left. i disabled most of the other bars like: editbar, navigationbar.. basicaly i kept only 5 of them: 
- file 
- miscelaneous 
- comment 
- menu
- sidebar

then i clicked save layout globaly, but, each time i restart q5go, few of them bars have been reseted to their default location, and reactivated so they show up again despite me having disabled them before.  some of them are saved i think, and some others aren't.
also, in new game, the sidebar is reported as disabled in the view menu while it is actualy being shown.

**Comment by bernds** [comment]
Try saving the specific layout? I think the general default may just set window size/position. Maybe I should remove that option.
I wasn't able to reproduce the sidebar issue in a quick test.

**Comment by nsklaus** [comment]
for the sidebar, please look at this screenshot, you can see the sidebar is not enabled in menu, but it is actualy being shown in game window.
![q5go](https://user-images.githubusercontent.com/6810861/88558022-49e2e880-d02b-11ea-934c-4f558fb174bf.png)
in this case i'm not even connected to igs. but it is the same when on igs.

**Comment by nsklaus** [comment]
i see two options to save the layout, and i did them both. but that did not properly saved the layout.
observer bar is always coming back. and it is the same for slider bar. 
you can see on previous post's screenshot: slider and sidebar are both displayed, despite being unchecked.

**Comment by bernds** [comment]
Could you attach your .q5gorc (in ~/.config/q5go normally)?
I can reproduce this for the slider (and I think I can partially see how that happens), but not the side bar. Is this happening in a normally opened board window, not just an online one? What happens when you toggle sidebar visibility in that state?

**Comment by bernds** [comment]
Actually, don't. It contains passwords.

**Comment by bernds** [comment]
I think I'm locking the conversation for a while to make sure you read the previous comment and don't accidentally post an unsanitized file.

**Comment by nsklaus** [comment]
(thank you for the warning about sanitizing debug file)

about the sidebar, when it is visible on screen despite being checked "off", 
if i click to check it "on" then nothing happen the first time (since it's already being shown). 
then aftwards it works normaly. "off" would remove it, and "on" would bring it back. 
this problem exist on all game windows, online or offline. i also see the same kind of things for observer bar. 

i will test again and report after a few hours, i made many games i need to take a pause for the moment. i think i will delete my local configuration and test from fresh, make a few screenshots i'll make the log from beginning and then report back.

**Comment by nsklaus** [comment]
ok, i made a test from fresh state (removed my old q5gorc file).
i made 3 connection to igs. each time i saved the layout i wanted.
i made 4 screenshots. 
for screenshot 1 to 3, i saved my layout ( i click save layout a few times ) then exited completly q5go. for screenshot 4 i just launched a new game without exiting q5go.

- the first screenshot shows plain default situation right after login in, starting a game i took a screenshot but i didn't change anything. you can see there's already a problem.
- the 2nd one is how i want my layout to be.
- 3rd and 4th ones shows my layout isn't being correctly applied.

there is the 3 sessions log files and my fresh q5gorc attached. (the archive is tgz, i just renamed it to .zip so github accepts it)
[q5go_layout.zip](https://github.com/bernds/q5Go/files/4989239/q5go_layout.zip)

**Comment by bernds** [comment]
Ok, I can now see how the "side bar is shown but unset in View" can occur when there is no saved layout. The menu item is checked/unchecked when restoring the layout. That's fixable. But I thought the issue also happened if you had a saved layout - can you clarify?

**Comment by bernds** [comment]
I think the sidebar issue is fixed now, but I'm still somewhat confused.

The observer thing is different, that is just enabled by default for all on-line games and not saved anywhere. It doesn't really fit with the "save layout" bit, since that saves per combination of docks - so observers on/off are two different layouts.
Maybe there should be a preferences option to disable showing it.

**Comment by nsklaus** [comment]
ok there was a few commits between the different issues, i grab fresh source to try it all.

**Comment by nsklaus** [comment]
i confirm, most of the layout is behaving fine now. there is only the observer bar that keeps coming back. as you've hinted at earlier. most of the ui layout settings remember saved state now, and seems well in sync with what's being shown as checked in the menus.

**Comment by nsklaus** [comment]
i'm closing this issue, as the layout is properly saved now. i'll open a separate issue for the observer bar that keeps coming back. many thanks for the work done. it is very appreciable, not having to setup layout every time i open q5go.
