### ISSUE TITLE
igs log isn't displaying correctly

### ISSUE THREAD

**Issue by nsklaus** [bernds/q5Go#37]
i think q5go doesn't display igs session output correctly.
for example it doesn't seem to show captures.

unless igs changed its protocol, here's what we should see
normal move:
```
1 8
15 Game 656 I: Maruhi (13 527 8) vs tataki (16 518 17)
15 264(B): B19 
```

move that capture opponent stones:
```
1 8
15 Game 656 I: Maruhi (13 527 8) vs tataki (16 518 17)
15 264(B): B19 C19 C18 C17 D18
```
(it's not from a real game but this is to illustrate that captures should  show up next to any given move)

**Comment by bernds** [comment]
Is that from the debug file? I don't think it would modify anything it saves to that file. Is there any actual problem here?

**Comment by nsklaus** [comment]
no, those are from a past session from 2018 i think, i was using telnet, observing a game.
that was what i got in my terminal.

**Comment by bernds** [comment]
Maybe it's different between client and non-client mode? In any case I don't see a real issue here, so closing.
