### ISSUE TITLE
automaticaly remove clear password from log file

### ISSUE THREAD

**Issue by nsklaus** [bernds/q5Go#38]
user password should not be saved in debug file.
some measures should be taken to avoid storing them in debug file.
it happen only once per session as far as i can tell. 
```
PASSWORD***
"1 1"
Password or 1 1: found:  "1 1"
"...send password"
send password  "xxxxxx"
>>  "xxxxxx"
PASSWORD***
```
apparently you're already able to tell when that event takes place, from its begining to its end (i mean the two strings "PASSWORD***" encompass the whole event). so just avoiding logging everything in between would be better. or replacing that with generic (password free) equivalent.

**Comment by nsklaus** [comment]
i will have to check it out to be able to confirm this, but,
i'm not sure the commit you made will be enough, since igs also reply with the password in clear.
`>>  "xxxxxx"`

**Comment by bernds** [comment]
No, that comes from sendTextToHost. That now has a "log" argument, so it should be fine.

**Comment by nsklaus** [comment]
also if the password in q5gorc could be stored crypted that would be nice.
there would be no issue of leaking password accidentaly.
