### ISSUE TITLE
link error on macOS

### ISSUE THREAD

**Issue by missdeer** [bernds/q5Go#4]
need to add something like below to `src/q5go.pro`:

```
macx :{
    LIBS += -framework CoreFoundation
}
```

**Comment by bernds** [comment]
Does it work after that? Thanks for trying it out on MacOS, it would be awesome if you could clone the project and provide binaries.

**Comment by bernds** [comment]
Dang. Wrong issue number.

**Comment by missdeer** [comment]
Yes, it works with macOS 10.14.3 & Qt 5.12.1.

**Comment by bernds** [comment]
Thanks!
