### ISSUE TITLE
analysis on boards larger than 25x25

### ISSUE THREAD

**Issue by cryptpark** [bernds/q5Go#40]
I make matches of different KataGo networks and play myself on 27x27 and 29x29 boards. after that it is interesting to do the analysis using the stronger KataGo network. but when setting the parameters, "preferences - computer go - change an engine configuration - board size (use for analysis)" - the limitation is 25x25. can this restriction be lifted?
probably in the "batch computer analysis" window "board size" is related to this, also limited to 25x25

**Comment by bernds** [comment]
Should be fixed now.

**Comment by cryptpark** [comment]
many thanks! everything is fine before I press "add to queue" in the "batch computer analysis" window, an error appears - "invalid response from gtp engine"

**Comment by bernds** [comment]
Should work now.

**Comment by cryptpark** [comment]
I am very grateful to you !!! works!
