### ISSUE TITLE
games selection window works on one system but not another.

### ISSUE THREAD

**Issue by wirelesstevmc** [bernds/q5Go#43]
I have compiled this on two of my (slackware64-current) systems now. On one system the 'game sekection' window docks all observed games into a single pane/window and on the other this does not seem to work. Even though I can enable/view the games selection window on the other system, each game wants to start in a separate window. Is this a compile feature? A library issue? Thanks.

**Comment by wirelesstevmc** [comment]
Sorry typo'd 'game sekection' above should read 'game selection' window.

**Comment by bernds** [comment]
I'm not entirely sure what you mean by game selection window? Do you mean the observation window for online games? There is a button on the client window toolbar to toggle behaviour between showing all games in a single window or opening individual ones. It's called "Observe mode", and it's to the right of the combo box for selecting the handicap range.

**Comment by wirelesstevmc** [comment]
That was it! Yes the "game selection" window is where the individual games/boards appear when you toggle "Observe mode" to single window. I must have found that button or accidentally clicked on the first build. Thanks a lot Bernds!
