### ISSUE TITLE
Feature request: it would be nice to be able to add multiple games at once

### ISSUE THREAD

**Issue by Trevoke** [bernds/q5Go#45]
e.g. a whole directory / subdirectories, or clicking on many games at once in the DB window.

**Comment by bernds** [comment]
Please describe more clearly what you have in mind. "Add" to what?

**Comment by Trevoke** [comment]
Ah, yes.

Okay, so:

When I open the Batch Computer Analysis window, I am greeted with analysis parameters, the Engine status, the "File to analyze" section, the job queue, and the completed jobs list.

The "File to analyze" section lets you select a single game, either through the filesystem or an available database. Once you have found the file you want to add, you can add that file to the job queue.

I have just gone through fifty games, which is to say that fifty times, here is what I did:
1. click on "DB"
2. click on the next game"
3. click on "add to queue"

Which is to say, I clicked 150 times. And that was only the first batch of games I want to feed through the analysis. I would much rather click only three times, for instance:

1. click on "find through file system"
2. select directory
3. add entire directory and subdirectories to queue

Or:

1. click on "find through database"
2. filter as desired
3. apply filters
4. ctrl-click or shift-click and select multiple games
5. click on "open"
6. add selected games to the queue


Let me know if I can provide any more context so that my request is clear :) 

Thanks for all the work you put on this project!

**Comment by bernds** [comment]
That helps, thanks. I'll try to think of something.

**Comment by bernds** [comment]
Sorry it took so long. Let me know if the "add directory" thing works for you.

**Comment by Trevoke** [comment]
Hi! I am getting a compilation error (I am on Linux):

```
In file included from ../src/analyzedlg.h:16,
                 from ../src/analyzedlg.cpp:4:
../src/qgtp.h: In member function ‘virtual void GTP_Controller::gtp_komi_failure(GTP_Process*, const QString&)’:
../src/qgtp.h:39:46: warning: unused parameter ‘p’ [-Wunused-parameter]
   39 |  virtual void gtp_komi_failure (GTP_Process *p, const QString &)
      |                                 ~~~~~~~~~~~~~^
../src/analyzedlg.cpp: In constructor ‘AnalyzeDialog::AnalyzeDialog(QWidget*, const QString&)’:
../src/analyzedlg.cpp:41:11: error: ‘enqueueDirButton’ was not declared in this scope; did you mean ‘enqueueButton’?
   41 |  connect (enqueueDirButton, &QPushButton::clicked, [=] (bool) { enqueue_dir (); });
      |           ^~~~~~~~~~~~~~~~
      |           enqueueButton
../src/analyzedlg.cpp: In member function ‘void AnalyzeDialog::enqueue_dir()’:
../src/analyzedlg.cpp:315:6: warning: unused variable ‘skipped’ [-Wunused-variable]
  315 |  int skipped = 0;
      |      ^~~~~~~
../src/analyzedlg.cpp:316:6: warning: unused variable ‘failed’ [-Wunused-variable]
  316 |  int failed = 0;
      |      ^~~~~~
make: *** [Makefile:1602: temp_/analyzedlg.o] Error 1
```

**Comment by Trevoke** [comment]
Correction, I downloaded the source from the release page and _that_ worked even though it's the same commit. I'm very confused but I'll take it I guess. Next message I'll report back on "add directory".

**Comment by Trevoke** [comment]
Okay - that feature works great, thank you very much!
