### ISSUE TITLE
Komi

### ISSUE THREAD

**Issue by reinnodroc** [bernds/q5Go#46]
I have an issue with analysis engine.

I use katago and get this message ; I couldn find where does this komi value come from and how to fix it.

<Working directory: /home/jl/bin/katago-v1.7.0-cpu-eigen-linux-x64
protocol_version
KataGo v1.7.0
Using koPOSITIONALscoreAREAtaxNONEsui0 rules initially, unless GTP/GUI overrides this
Loaded config /home/jl/bin/katago-v1.7.0-cpu-eigen-linux-x64/gtp_example.cfg
Loaded model /home/jl/bin/katago-v1.7.0-cpu-eigen-linux-x64/g170e-b15c192-s1305382144-d335919935.txt.gz
Model name: b15c192-s1305382144-d335919935
GTP ready, beginning main protocol loop
=1 2
boardsize 19
=2
clear_board
=3
komi 7,50
?4 Expected single float argument for komi but got '7,50'
quit>

**Comment by bernds** [comment]
Are you using the latest version of q5go? This was supposed to be fixed by commit d78530650b897bc03b38e095eff9553458a9e23f.

**Comment by bernds** [comment]
Assuming this is fixed in the latest version. Please reopen if you can confirm that it still happens in 2.0 or above.
