### ISSUE TITLE
No sound will play regardless of settings

### ISSUE THREAD

**Issue by Aicaya** [bernds/q5Go#47]
Followed the instructions to compile on linux and I noticed that none of the sounds will play.  No errors show on the terminal while running, either.

Compiled on Arch Linux with latest packages and using ALSA for sound.  Tested both the 2.0 release and the latest git pull.

**Comment by bernds** [comment]
Hmm. Not much to go on. Do other Qt applications play sounds (Clementine, or KDE games)?

**Comment by Aicaya** [comment]
Yeah, I have both qGo and Qmmp installed and they play sounds perfectly fine.

Really wish I could give something else to go on, but I really don't know how to debug this one.  The only time I got a kind of warning message was when running it with apulse to see if it was an ALSA-only thing (`QObject::connect: Cannot queue arguments of type 'QTextCursor' (Make sure 'QTextCursor' is registered using qRegisterMetaType().`), but that only happened when placing stones so it still doesn't explain why there weren't any sounds when passing.  None of the compile-time warnings seemed like they were sound-related, either.

I did have a question based on my attempts, though: Are the sound files part of the binary or are they meant to be installed on a separate folder?  I ask because qGo has them on a separate location after installing (`/usr/share/qgo/sounds/`, if using the Arch package) but q5Go doesn't install them anywhere in the system.

**Comment by bernds** [comment]
The sounds are part of the binary, they are now treated as resources, precisely to avoid relying on external files.

**Comment by bernds** [comment]
Dumb question, but are the sounds enabled (there is a mute button, and individual toggles in the preferences dialog)? The best way to make sure would be to go into the settings and toggle the sound checkboxes, it should play the sound that's being toggled.

**Comment by Aicaya** [comment]
They are, yeah.  All the checkboxes are toggled and I even repeatedly toggled the mute button to see if it did anything.

**Comment by bernds** [comment]
Still no idea, and no other reports of this - assuming some sort of configuration problem.
