### ISSUE TITLE
Can q5Go store variations temporarily when pausing analysis?

### ISSUE THREAD

**Issue by HackYardo** [bernds/q5Go#48]
I know I can store variations when analyzing, but when I pause analyzing, all the variations are gone. If use Sabaki, I can use "final_score" to store variations temporarily on the board and the analysis is paused, but I can't store variations because the author of Sabaki doesn't like variations as far as I know. I hope to choose variations to store when pausing analysis because real-time analysis will make my poor laptop hot.

**Comment by bernds** [comment]
It sounds like you're using live analysis (i.e. not the batch analysis dialog). You should be able to shift-click on one of the suggested moves to store the variation. In the View menu, bring up the "Diagrams" pane, where you can examine all variations that are marked as a diagram.
Is this what you are looking for?

**Comment by HackYardo** [comment]
I will try it tonight, the laptop isn't on my hand. Thanks!

**Comment by HackYardo** [comment]
Well, it is not what I want to say. The all colorful variations generated by a engine are holding on the board after live analysis paused, then I could mark some of them to store into diagrams or smart go format files, rather than marking and analyzing at the same time.

**Comment by HackYardo** [comment]
Well, it is not what I want to say. The all colorful variations generated by a engine are holding on the board after live analysis paused, then I could mark some of them to store into diagrams or smart go format files, rather than marking and analyzing at the same time.

**Comment by HackYardo** [comment]
seems too long to pick it up
