### ISSUE TITLE
Invalid decimal point in SGF when using different locale

### ISSUE THREAD

**Issue by jest** [bernds/q5Go#52]
I'm using Polish locale on my system (`pl_PL.UTF8`), in which the decimal point is defined as comma (`,`).

The comma is used for a komi field in user interface of "Game information", which is fine. However, when writing the game to SGF, a comma is also written, e.g. `KM[6,5]`, whereas the SGF standard requires dot to be used (i.e. `KM[6.5]`).

This results in broken SGF file, which cannot be read back into qGo or other editors ("Errors found in SGF file").

I suspect other tags containing real values can also be affected.

The workaround is to edit SGF in some text editor and replace comma with dot.

**Comment by bernds** [comment]
Should be fixed now. You should be able to read bad SGF files and write them out again to fix them.

**Comment by jest** [comment]
Thanks, works great!
