### ISSUE TITLE
sgf auto-play

### ISSUE THREAD

**Issue by peanatsu** [bernds/q5Go#53]
is it possible to auto-play sgf files? that is, to have the board automatically go through the game moves at some set time interval?

Like cgoban3's shift-click on next-move button, which starts playing the moves without user input.

I've seen some reference to an auto-play feature in the changelog and in the translations, but couldnt figure out if it's still a feature in q5go and how to use it. (The fact that auto-play interval settings seems to be gone from the preferences makes me think it isnt currently supported)

sooo.. is it possible? if so how? if not, is it likely to be implemented?

**Comment by bernds** [comment]
This used to be a feature in qgo, but I discarded it because it was in the way of restructuring the code for q5go, and because I didn't really see a need.

Now that I've got at least one user requesting it, I'll think about whether to add it again.

**Comment by peanatsu** [comment]
That's great! Thanks for all your hard work btw, it's really appreciated!

>  I discarded it because [...] I didn't really see a need

well, going through a long game it can become a bit tedious hitting the next-move key 300-something times in a row. IIRC auto-play is also a feature on wbaduk and tygem official clients, though it's been a while since I played there, so I could be wrong.

**Comment by bernds** [comment]
I just find it odd that someone reviewing a game wouldn't want to spend varying amounts of time per move - skipping through known joseki and spending more time in difficult fights. That's just to say, I don't really get it, but I'll look into it.

The main issue I have is (as usual) one of user interface. I don't want someone to accidentally enable autoplay and then wonder what the program is doing and how to turn it off again. It needs to be very clear. Maybe open a separate window?

**Comment by cryptsport** [comment]
> Now that I've got at least one user requesting it, I'll think about whether to add it again.

if there is still an opportunity to include analysis, that's great! about a year ago I turned to you with a similar request:
"if it were possible to open the sgf, turn on autoreplay, and run the analysis - that would be fantastic!
maybe it's not difficult to do it? :)" https://lifein19x19.com/viewtopic.php?p=259163#p259163

**Comment by peanatsu** [comment]
> I just find it odd that someone reviewing a game wouldn't want to spend varying amounts of time per move

two things: first, you may not want to review at all, but simply go through the moves. second, say you want to review, but not the entire game, only key sections of it, say an interesting fight that starts at move 183. Currently you'd have to hit the next-move button 183 times until you reach an interesting position you want to review.

btw I checked gGo (an older java pandanet client / sgf editor) and it also has auto-play. I believe most chess software also has automatic replay functionality. examples include lichess, xboard, scid and many others I'm sure.

> The main issue I have is (as usual) one of user interface. I don't want someone to accidentally enable autoplay and then wonder what the program is doing and how to turn it off again

simply add a play/pause-button (like music-player play-button) that toggles auto-play to the navigation toolbar.

If you want to be paranoid about it you could make auto-play "fragile" so that it will stop on any user input, like clicking anywhere or pressing any key, though I'd suspect most users will be familiar with the feature, since, as mentioned before, it's pretty ubiquitous.

A slightly less paranoid way would be to make auto-play stop on any navigation command (like next-move, or previous-move, mouse-scroll, placing a stone, etc), in addition to the toggle button of course. That seems pretty intuitive to me.

**Comment by bernds** [comment]
> Currently you'd have to hit the next-move button 183 times until you reach an interesting position you want to review.

That's what the slider below the board is for. Maybe it's disabled in your View menu? Just click once and drag - in my view a much more convenient solution than autoplay.

Anyhow, I've added an autoplay implementation.
