### ISSUE TITLE
matches with inverted colors miscounted in pattern search

### ISSUE THREAD

**Issue by nanzi** [bernds/q5Go#64]
Maybe it‘s a corner case in pattern search. 
I searched sansan in katago-60b-457 rating games and got 78 matches, 
which q5go told me 3 matches in white(inverted) colors.
But after I counted with screen-print in case of missing or double counting, there were only 2 sgfs.

[kata1-b60c320-s4577723904-d2458479936.tar.gz](https://github.com/bernds/q5Go/files/8798568/kata1-b60c320-s4577723904-d2458479936.tar.gz)

![Screenshot_2022-05-30_08-40-01](https://user-images.githubusercontent.com/2120755/170999654-693b20a2-d92d-46ef-ad40-7ee9ae69db7c.jpg)

![Screenshot_2022-05-30_08-44-02](https://user-images.githubusercontent.com/2120755/170999714-294ff7ba-a16f-4158-a965-4ffcbe8e75f9.jpg)

**Comment by nanzi** [comment]
Excuse me, and what does "136+3=139 matches" indicate? In some search the invert color number is reliable(by coincidence?)

**Comment by bernds** [comment]
Could be a problem with the symmetry of the pattern causing double counting. Not sure yet.

**Comment by bernds** [comment]
I think this commit should fix it - please verify whether you still see problems.

**Comment by nanzi** [comment]
Cool. I have compiled the latest commit and both pattern counting (got 2 now) and game sum counting (got 76+2=78 now) are fixed now.

**Comment by nanzi** [comment]
Cool. I have compiled the latest commit and both pattern counting (got 2 now) and game sum counting (got 76+2=78 now) are fixed now.
