### ISSUE TITLE
pattern search statistics has a wrong result in this case

### ISSUE THREAD

**Issue by nanzi** [bernds/q5Go#65]
Q5go pattern searching on [katago-60b-457 rating games](https://github.com/bernds/q5Go/files/8798568/kata1-b60c320-s4577723904-d2458479936.tar.gz)
When I had this pattern search result, G has totally 3 white matches which wrongly showed in statistics bar. H and F have mixed color move match, but G was switched with H.
Board color seems fine, statistics panel has something wrong.....

![Screenshot_2022-05-30_09-22-23](https://user-images.githubusercontent.com/2120755/171001443-f9abec22-de46-4b8e-bed8-e63af171b47f.jpg)

**Comment by nanzi** [comment]
Test on [kata1-b60c320-s5763300608-d2802381103.tar.gz](https://github.com/bernds/q5Go/files/8799019/kata1-b60c320-s5763300608-d2802381103.tar.gz)
indicates G-H, I-J , K-L are switched in statistic panel.

![Screenshot_2022-05-30_10-16-00](https://user-images.githubusercontent.com/2120755/171010895-a0f014da-d541-47ae-90f0-c3b3b966aff9.jpg)
![Screenshot_2022-05-30_10-16-10](https://user-images.githubusercontent.com/2120755/171010901-c01302ca-a804-4f9e-84cd-66f026ac9d82.jpg)

**Comment by bernds** [comment]
I've pushed out an update. Let me know if this is better for you.

**Comment by nanzi** [comment]
fixed
