### ISSUE TITLE
Feature request: add numbers on stones starting from 1 in variations

### ISSUE THREAD

**Issue by Trevoke** [bernds/q5Go#68]
An option to toggle whether a variation shows completely normally or with numbers (so that you can see visually where divergence from the main tree is and track it sequentially) would be nice!

**Comment by bernds** [comment]
I'm not sure what you mean. The variations I can think of, in analysis, are shown with numbers. Could you explain in more detail what you have in mind?

**Comment by Trevoke** [comment]
Sure! Here's two screenshots. The first is of the main branch, the second is of a variation branch. I think it would be nice if the moves from the variation branches had numbers on them. In this particular case, this is the third move of the variation, so numbers 1, 2, and 3 would be on respective stones.

![image](https://user-images.githubusercontent.com/67913/174452856-62d43b70-c117-409e-8ced-b1b6135563bc.png)

![image](https://user-images.githubusercontent.com/67913/174452874-f364da59-daa9-498e-81a3-9f3b95125e60.png)

**Comment by bernds** [comment]
You can already number the moves in the View menu. I've added a prefs option to control how it behaves for variations off the main line.

**Comment by bernds** [comment]
I've come up with an alternative which is probably nicer. You can try it out on the alternative-numbering branch. I suspect I'll switch it over, but if you have input it would be useful.

**Comment by Trevoke** [comment]
If I built the correct thing, I have two options, short and long, but I can't understand what should be different between the two of them. It looks like they both show the same thing, I went as far as 30 moves down a variation in case it only showed the last ten moves or something, but nothing. What am I missing?

**Comment by bernds** [comment]
It's for when variations branch off of variations. It chooses different starting points in that case.
