### ISSUE TITLE
Why does the evaluation graph not show an evaluation of each move in the game

### ISSUE THREAD

**Issue by metaperl** [bernds/q5Go#69]
![q5go_fPfXD8mC9Z](https://user-images.githubusercontent.com/21293/188081930-638ad504-a2ae-4473-8484-8e7c448fab39.png)

In this photo, the evaluation graph only shows a move or two instead of an evaluation of all moves in the game.

How does one get an evaluation of all moves in the game?

**Comment by bernds** [comment]
It looks like you enabled live analysis and only looked at two positions with it.

Either scroll through the game to build up more data (or use the autoplay functionality), or run the game through the batch analysis.
