### ISSUE TITLE
Invalid move by the engine

### ISSUE THREAD

**Issue by jun63cn** [bernds/q5Go#73]
compiled by commit e2dd1e69  Win10 SYS
![Snipaste_2022-12-15_11-15-18](https://user-images.githubusercontent.com/30382868/207765084-1c80a9e5-c54c-4b86-b085-57b4aae8ec16.jpg)

**Comment by bernds** [comment]
Is this a recent version of KataGo? I've also started seeing this, and if I enable more debug output it does seem to be playing on an existing stone.

**Comment by jun63cn** [comment]
Yes, It‘s recent gpu-backend-cleanup branch.
