### ISSUE TITLE
how to make two engines play each other

### ISSUE THREAD

**Issue by jwaldmann** [bernds/q5Go#75]
It seems the GUI assumes that at least one player is human (that is, uses the mouse to enter moves). Is it possible to run (start and watch) a game between two engines?  (cgoban could do this? ... but that's long ago)

**Comment by bernds** [comment]
It's perhaps a bit hidden, but the client window (opened by the "play online" button) has a menu that includes computer vs computer play. It would probably be a good idea to make that available elsewhere too.
