### ISSUE TITLE
some non-UTF8 encoded SGF files don't have correct CA[] property set

### ISSUE THREAD

**Issue by missdeer** [bernds/q5Go#8]
Seemly SGF files downloaded from http://weiqi.tom.com/php/listqipu.html are encoded as 'ISO-8859-1' aka 'Latin1', but they don't have correct CA[] property set, thus CJK characters can't be displayed by q5Go correctly.
Maybe charset detection and convertion to UTF-8 before loading SGF is need.

**Comment by bernds** [comment]
Could perhaps add an option to the new file selector to choose and enforce a character set for the file to be loaded. That would show the result in the player name preview.
This probably won't be very high on my list of priorities for a while - the SGF files are just invalid after all.

**Comment by missdeer** [comment]
i have made a quick & dirty change, it works :)
https://github.com/missdeer/q5Go/commit/d72f290c961a4260263ac1a2923430fcfaa2af0b

**Comment by bernds** [comment]
Looks pretty close to what I had in mind - I've added two comments to the change.

**Comment by missdeer** [comment]
https://github.com/missdeer/q5Go/commit/d8e838120a33d4a9310330f70b391b193cb0a8aa
change as your suggestion, and show a text codec with its aliases in a single combo box item

**Comment by bernds** [comment]
Alright, I'll look at integrating this. Some problems still: the combo box is much too wide (squashing the preview), because of all the aliases. I'm considering just dropping these. Also - do we actually need all the encodings, or is there a reasonable subset we can use (which would be more user-friendly, requiring less scrolling)?

The old qGo used to have a list of Big-5, EUC-JP, JIS, Shift-JIS, EUC-KR, GBK and Tamil TSCII. Do you know if anything important is missing from that list? What encoding did you end up using for the files from the above link?

**Comment by missdeer** [comment]
I think this list can cover the most cases:
Simplified Chinese: GBK, GB2312, GB18030
Traditional Chinses: Big5
Korean: EUC-KR
Japanese: EUC-JP, ISO-2022-JP, Shift-JIS
UTF-8

**Comment by bernds** [comment]
This is all a bit confusing... I have no experience with any of these encodings, so I'll just keep asking questions.

The list returned by Qt contains multiple instances of "GBK", for example. If we look at the mib value 2025, it is called "GBK" in the combo box, but in the IANA document, it shows up as GB2312, which is missing from the list Qt gives us.

Wikipedia claims that 2312 is older than GBK, and GBK is in turn superseded by GB18030, but that they should be backwards compatible. There's also a page in the Qt documentation which suggests the same. So - out of these three, do we really need anything other than GB18030 (which can be found unambiguously)?

**Comment by bernds** [comment]
Well, I did what seemed best and pushed out the result. Assuming this is fixed for now, so closing.
