### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by Taxicletter** [bernds/q5Go#81]
This error:
```
$ qmake /home/xxx/Downloads/q5Go-master/src/q5go.pro PREFIX=/home/xxx/Programmas
Info: creating stash file /home/jonathan/.qmake.stash
Project ERROR: Unknown module(s) in QT: multimedia svg
```
What can I do?

EDIT:
The svg packet is installed:

```
 sudo dnf install qt5-qtsvg-devel
Laatste metadata-expiratie-check: 0:36:18 geleden op di 23 jul 2024 12:52:34.
Pakket qt5-qtsvg-devel-5.15.14-1.fc40.x86_64 is al geïnstalleerd.
Afhankelijkheden opgelost.
Niets te doen.
```

**Comment by bernds** [comment]
You probably need to install a few more packages. This kind of thing was discussed before here:
https://github.com/bernds/q5Go/issues/29
Hope this helps.

**Comment by Taxicletter** [comment]
I'm sorry, it doesn't help...
I have these packages installed:

```
qt6-qt5compat
mingw64-qt5-qmake
mingw64-qt5-qtmultimedia
qt5-qtmultimedia-devel
qt5-qtmultimedia
```
These packages mentioned in #29 I cannot find in Fedora:

```
libqt5svg5-dev
qtmultimedia5-dev
qt5-qmake
qt5-default
```
I used dnf search and installed what most closely looked like above packages.

This text
```
-!versionAtLeast(QT_VERSION, 5.7.0) {
-    error("This program requires Qt 5.7 or newer")
-}
```
Is already commented out in _q5Go-master/src/q5go.pro_ by default, I checked.

So I think I did anything mentioned. Where can I find which packages are missing in Fedora?

**Comment by bernds** [comment]
Is Qt6 installed in parallel? Maybe it's picking up the wrong qmake.
